#!/bin/bash

set -e

cd $(dirname $0)

TARGET=main
FLAGS="-libs str,dynlink,unix,fileutils -cflags -I,+fileutils -lflags -I,+fileutils"
FLAGS="$FLAGS -yaccflag -v -lflag -g"
OCAMLBUILD=ocamlbuild

ocb()
{
  $OCAMLBUILD $FLAGS $*
}

rule() {
  case $1 in
    clean)  ocb -clean;;
    native) ocb $TARGET.native;;
    byte)   ocb $TARGET.byte;;
    all)    ocb $TARGET.native $TARGET.byte extensions/core/{closure,misc}.cm{o,xs};;
    depend) echo "Not needed.";;
    *)      echo "Unknown action $1";;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi


