#!/bin/bash

set -e

cd $(dirname $0)

EXTENSIONS=$(echo extensions/{core,spl,compat}.cm{o,xs})
TARGET=main
FLAGS="-libs str,dynlink,unix,fileutils -cflags -I,+fileutils -lflags -I,+fileutils"
FLAGS="$FLAGS -yaccflag -v"
OCAMLBUILD=ocamlbuild

ocb()
{
  $OCAMLBUILD $FLAGS $*
}

rule() {
  case $1 in
    clean)  ocb -clean;;
    native) ocb $TARGET.native;;
    byte)   ocb $TARGET.byte;;
    all)    ocb $TARGET.native $TARGET.byte $EXTENSIONS;;
    depend) echo "Not needed.";;
    *)      echo "Unknown action $1";;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi


